🐞 fix: cmaketools can't delect preset
lukka/CppCMakeVcpkgTemplate pull request #24
Opened 2024-04-13 16:24 UTC by gukazma

vscode plugin ``cmake tools`` can't delect ``CMakePresets.json`` that contains:
```
"$schema": "https://cmake.org/cmake/help/latest/_downloads/3e2d73bff478d88a7de0de736ba5e361/schema.json"
"toolchainFile": "${sourceDir}/vcpkg/scripts/buildsystems/vcpkg.cmake"
```
I have deleted and modified these two lines to ensure that the plugin can run properly

2024-04-13 18:59 UTC, lukka commented on CMakePresets.json
> -            "toolchainFile": "${sourceDir}/vcpkg/scripts/buildsystems/vcpkg.cmake"
CMakePresets.json v3 and up should support the `toolchainFile` property, could you please double check?

2024-04-13 19:00 UTC, lukka commented on CMakePresets.json
> -    "$schema": "https://cmake.org/cmake/help/latest/_downloads/3e2d73bff478d88a7de0de736ba5e361/schema.json",
Right, CMake-Tools is supporting CMakePresets.json version 6, but the $schema attribute was introduced in version 8.

2024-04-16 09:44 UTC, gukazma commented on CMakePresets.json
> -            "toolchainFile": "${sourceDir}/vcpkg/scripts/buildsystems/vcpkg.cmake"
But cmake-tools plugin recognizes CMakePresets.json with toolchainFile attribute

2024-04-16 09:44 UTC, gukazma commented on CMakePresets.json
> -            "toolchainFile": "${sourceDir}/vcpkg/scripts/buildsystems/vcpkg.cmake"
但是cmake-tools插件不识别带toolchainFile属性的CMakePresets.json

2024-04-16 09:45 UTC, gukazma commented on CMakePresets.json
> -            "toolchainFile": "${sourceDir}/vcpkg/scripts/buildsystems/vcpkg.cmake"
But the ``cmake-tools`` plugin does not recognize ``CMakePresets.json`` with ``toolchainFile`` attribute

2024-04-17 17:12 UTC, lukka commented on CMakePresets.json
> -            "toolchainFile": "${sourceDir}/vcpkg/scripts/buildsystems/vcpkg.cmake"
@gukazma works for me on CMake Tools `v1.17.17`.

The `$schema` option needs to be dropped from the CmakePresets.json, but the `toolchainFile` works just fine, here the content of the Output->CMakeTools pane (I enabled verbose output in `setttings.json` with `"cmake.loggingLevel": "debug"`):

```
[expand] expanding cmake
[main] Configuring project: CppCMakeVcpkgTemplate 
[main] Saving open files before configure/build
[driver] Removing /Users/user/github/CppCMakeVcpkgTemplate/builds/ninja-multi-vcpkg/CMakeCache.txt
[driver] Removing /Users/user/github/CppCMakeVcpkgTemplate/builds/ninja-multi-vcpkg/CMakeFiles
[expand] expanding /Users/user/github/CppCMakeVcpkgTemplate
[driver] Start configure 
[driver] Running pre-configure checks and steps
[expand] expanding /Users/user/github/CppCMakeVcpkgTemplate
[cmakefileapi-driver] Configuring using preset
[cmakefileapi-driver] Invoking CMake /opt/homebrew/bin/cmake with arguments ["-DCMAKE_TOOLCHAIN_FILE=/Users/user/github/CppCMakeVcpkgTemplate/vcpkg/scripts/buildsystems/vcpkg.cmake","-S/Users/user/github/CppCMakeVcpkgTemplate","-B/Users/user/github/CppCMakeVcpkgTemplate/builds/ninja-multi-vcpkg","-G","Ninja Multi-Config"]
[proc] Executing command: /opt/homebrew/bin/cmake -DCMAKE_TOOLCHAIN_FILE=/Users/user/github/CppCMakeVcpkgTemplate/vcpkg/scripts/buildsystems/vcpkg.cmake -S/Users/user/github/CppCMakeVcpkgTemplate -B/Users/user/github/CppCMakeVcpkgTemplate/builds/ninja-multi-vcpkg -G "Ninja Multi-Config"
```

I am using cmake `v3.27.7`.

2024-04-18 16:25 UTC, lukka requested changes
please drop only the schema attribute, and keep the toolchainFile one.

2024-04-28 07:09 UTC, lukka commented
This PR has been superseded by https://github.com/lukka/CppCMakeVcpkgTemplate/pull/25

2024-04-28 07:09 UTC, closed without merging